### ISSUE TITLE
Type the `count` variable for i18n.translate as `number`

### ISSUE THREAD

**Issue by qq99** [Shopify/quilt#1069]
## Overview

Assume the dictionary:
```json
{
  "SomePath": {
    "someKey": {
      "one": "{count} thing.",
      "other": "{count} things.",
    }
  }
}
```

1.  Try to `i18n.translate('SomePath.someKey', { count: someVariable })` when `someVariable === '1'`
2. 💥 See `Missing translation for key: SomePath.someKey`
3. Tweak it to `i18n.translate('SomePath.someKey', { count: Number(someVariable) })`
4. ✅ It works now

## Motivation

Why is this a problem?  Often `someVariable` might be powered by your component state, grabbed from a `<TextField >` or something.

The typings allow you to put a non-number in there, but it won't look up the keys properly.

This caused me some large period of pain until I finally realized what was going on.

Thoughts:
- typing it as `number` (since `count` requires an actual `number` to work properly) would definitely help you find the problem in a timely manner 
- doing the conversion internally if `count` variable is present might be a nice thing to try, but might be extra calls to `Number(...)` for 99% of the cases

So, it seems like typing the `count` key might be the best solution

**Comment by rexmac** [comment]
So, my first attempt at this was to just add an optional `count` key to the replacement dictionary interfaces, but this forces the addition of `undefined` as a type for the `[key: string]` values, which I'm fairly certain is not something we want to allow. 😞 

As far as I can tell, having an optional key triggers an implied `undefined` type for `count` (due to `strictNullChecks: true` in tsconfig.json?), and because `count` also matches the string index ('[key: string]`), then that type must also include `undefined`.

```ts
export interface PrimitiveReplacementDictionary {
  count?: number;
  [key: string]: string | number | undefined;
}

export interface ComplexReplacementDictionary {
  count?: number;
  [key: string]: string | number | React.ReactNode | undefined;
}
```

**Comment by qq99** [comment]
From https://basarat.gitbooks.io/typescript/docs/types/index-signatures.html

I think you have to use intersection type?

```tsx
type FieldState = {
  value: string
}

type FormState = {
  isValid: boolean  // Error: Does not conform to the index signature
  [fieldName: string]: FieldState
}
```
vs
```tsx
type FieldState = {
  value: string
}

type FormState =
  { isValid: boolean }
  & { [fieldName: string]: FieldState }
```
