### ISSUE TITLE
Change `navigationCount` from `private` to `readonly`

### ISSUE THREAD

**Issue by theodoretan** [Shopify/quilt#1128]
## Overview

Currently the `navigationCount` property on Performance is private.
https://github.com/Shopify/quilt/blob/57b6720d7b661553b0da8579ca1b0922259a7165/packages/performance/src/performance.ts#L51

We'd like to propose that the property is `readonly` instead so we can access it without typescript throwing errors.

## Type

- [x] Changes to existing features

## Motivation

We're tracking the load-time metrics using the `lifecycleEvent` listener and it is eventually going to be on each page level component to see how long it takes for `ttfb`, `fcp`, and `DOMContentLoaded`. However, because we're using client-side routing, these values aren't being updated since those events aren't happening. 

We want to use the `navigationCount` to ensure we only send the events on the initial load.

Was there a reason why `navigationCount` was private when building the package initially?

**Comment by lemonmade** [comment]
`Navigation`s have a public [`metadata` property](https://github.com/Shopify/quilt/blob/master/packages/performance/src/navigation.ts#L36). This property is an object with some non-timing related information about the navigation, including its [index since the first navigation](https://github.com/Shopify/quilt/blob/master/packages/performance/src/types.ts#L114). I think using that property should be all you need. If all you want to know is whether this was the first (full page) navigation or a subsequent (incremental) navigation, you can use [`Navigation#isFullPageNavigation`](https://github.com/Shopify/quilt/blob/master/packages/performance/src/navigation.ts#L30-L32). This is what web uses to compute a [`fullPageNavigation` tag for Datadog](https://github.com/Shopify/web/blob/db72dd8e3a43618f484a21990b3df82ad8bcae62/server/router/middleware/client-metrics/utilities.ts#L11).
