### ISSUE TITLE
Terms of Use?

### ISSUE THREAD

**Issue by chowey** [Shopify/quilt#1156]
I noticed that `@shopify/address` is actually making calls to a graphql endpoint: https://country-service.shopifycloud.com/graphql

The `@shopify/address` package seems to be MIT licensed. However, what are the terms of use for this graphql endpoint? Or is just fully free and open?

**Comment by lemonmade** [comment]
Thanks for pointing this out, @chowey. You're correct that `@shopify/address` just makes unauthenticated request to a service operated by Shopify. As a result, for the time being, it is best to treat that package as for Shopify internal use only. I'll make a note of that on the README.

cc/ @christianblais if you have anyone you'd like to ping/ if you want to start a discussion here around whether we will have ways of opening it up beyond our internal apps.

**Comment by ilamp** [comment]
Can this package be opened for external use for Shopify App Developers? We can most definitely use it.

**Comment by except** [comment]
Is there an update to this issue?

**Comment by plentz** [comment]
I think there are two approaches that we can use for this:
- allow country-service to serve requests to any domain. This is the easiest approach implementation wise, but will add some extra load to our service. Since we have no idea of how many people and the size of their apps/traffic would be, it's a bit tricky. But the data served by country-service is basically static (no database calls or anything like that) it does not worry me much.
- check if the current domain is operated by Shopify and if it's not fall back to a static version of the data in a json included in the library (something like we do in web https://github.com/Shopify/web/pull/31129). This would solve the problem and the "worst" that could happen is the local json to not be as updated as the live version in country-service until we release a new version of the library (which should not be a big deal)
