### ISSUE TITLE
Allow react-i18n to generate translations for specific locale(s)

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/quilt#1170]
## Overview
We're trying to:
- Slim down the webpack metadata required to serve react-i18n translations in large apps
- Get all users on an equal footing (right now, _everyone_ has to download the fallback locale's translations)

To achieve this, I think that we need a webpack plugin that:
- Accepts locale(s) + fallback locale
- Includes translations for the locale _directly beside_ their component in the JS bundle
- Merges in fallback translations for anything missing from the locale's translations

@michenly is already working on a webpack plugin, and this could possibly be an extension of that.

## Type
- [x] New feature

## Motivation
Really big download sizes in our larger apps :/

**Comment by GoodForOneFare** [comment]
cc @lemonmade because you have useful thoughts on implementation details

**Comment by lemonmade** [comment]
So, my vision for the "final" state of this would be a Webpack plugin that has configurable behaviour for how to handle an empty `useI18n`/ `withI18n`, because how to handle those translations is likely something that depends on the size of the app and how fine-grained they have split their translations.

Our default approach could continue being what it is now: add a sync import for the fallback translation, use it as the `fallbackTranslations` option, create a unique ID based on the file for the `id` option, and create a function that does a `lazy-once` async import for any other locale. However, we definitely want at least one other option: sync import a fallback translation for the `fallbackTranslations` option, unique ID from the name of the file for the `id` option, and a sync import for a specified locale (build per locale; what we want for web). Conceivably, this option could be further refined in the future to group all locales with the same language code together. Additionally, we can think of other strategies that might be effective (sync import all translations, sync import a list of "priority 1 languages" and async the rest, etc, but that can come from actual needs later on.

**Comment by GoodForOneFare** [comment]
Fixed by `@shopify/react-i18n`'s new `from-dictionary-index` mode: https://github.com/Shopify/quilt/pull/1197.  `sewing-kit@sewing-kit@0.114.0` uses this mode is `sewing-kit build --locale <locale>` is specified.
