### ISSUE TITLE
[graphql-testing] Not getting types for matchers

### ISSUE THREAD

**Issue by Tzelon** [Shopify/quilt#1216]
## Overview
Hey,
I imported the matchers from `@shopify/graphql-testing/matchers` .
The matchers are working, but I'm not getting its types in my tests.

...

## Consuming repo
@shopify/graphql-testing
...

Thank you

**Comment by GoodForOneFare** [comment]
Hi, @Tzelon!  This problem is typically due to a lack of an explicit _TypeScript_ import.  Can you confirm that you have:
* A file with a `.ts` extension (e.g., Shopify repos typically have a `tests/each-test.ts`) file
* That it does `import '@shopify/graphql-testing/matchers';`
* The this file is executed before every test suite

If that doesn't help, please provide a small, self-contained example repo that we can 👀 Thank you! 😄

**Comment by Tzelon** [comment]
Hey, @GoodForOneFare thank you for the reply.
Yes, it solved the problem. I have put the import in my setupFilersAfterEnv, as I do with `@testing-library/jest-dom/extend-expect`. For some reason, those types work from there.

Thank you again.
