### ISSUE TITLE
Online Token Additional Data?

### ISSUE THREAD

**Issue by kisuka** [Shopify/quilt#1420]
Is there a way to get the additional data returned with online access tokens? Defined here: https://shopify.dev/tutorials/authenticate-with-oauth

I noticed in the Koa Shopify Auth, it just [returns only the access token back](https://github.com/Shopify/quilt/blob/5ba6cd69793a071950467c5f09c4dee9e93d15d0/packages/koa-shopify-auth/src/auth/create-oauth-callback.ts#L56).

`const accessTokenData = await accessTokenResponse.json();`
`const {access_token: accessToken} = accessTokenData;`

Do I have to somehow ignore the koa auth's callback and write my own from scratch just to get if the current user is the owner or not?

How come there isn't a way to hook into the callback or have it return the entire response from Shopify?

**Comment by TheMallen** [comment]
It sounds like a relatively simple fix to provide more of the destructed JSON, we may not be able to prioritize it immediately but PRs are welcome :)

**Comment by hameeddamee** [comment]
> 
> 
> It sounds like a relatively simple fix to provide more of the destructed JSON, we may not be able to prioritize it immediately but PRs are welcome :)

It doesn't look like a simple fix as we have battling with it for quite some days now. It would be nice if you can point us in the direction of how to get it done. Since the tutorial pointed out that we get `associated_user` object, it is only fair that it is made available in the package. Or an help here would be greatly appreciated

**Comment by kevinpjones** [comment]
@TheMallen PR submitted for this issue, awaiting a merge
