### ISSUE TITLE
Export @shopify/react-i18n/babel as a babel macro?

### ISSUE THREAD

**Issue by emroussel** [Shopify/quilt#1486]
## Overview

We want to use `@shopify/react-i18n/babel` in a project bootstrapped with [Create React App](https://github.com/facebook/create-react-app/) without ejecting. I'm not very familiar with how babel plugins work, but I know Create React App supports babel macros, so it seems like exporting the current plugin as a macro would allow us to use it.

Is this a correct assumption and something you would be willing do to?

## Type

- [x] New feature
- [ ] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing,
> or what else makes you think this should be in `quilt`?

I don't know how much code changes are needed to export a regular babel plugin as a macro, but it feels like it should be minimal while providing wider support.

## Labels

_I do not have permissions to add labels._

**Comment by emroussel** [comment]
@TheMallen not sure if you're the right person to ping, but wondering if you have any idea about this or who can give me more context?

**Comment by emroussel** [comment]
@TheMallen pinging you again about this in case you know how to proceed or you know who I could talk to

**Comment by michenly** [comment]
@emroussel, TheMallen is on intermission so I will try my best to help with your question.

You can currently uses `@shopify/react-i18n/babel` as long as you have access to the project's webpack config.

From a quick research thou, it does seem like if your requirement is to use create-react-app without ejecting then this method would be a no go. 

The babel macro seems like a very interesting idea and can likely resolve your issue. 

However, since 80% of the application we support uses sewing-kit and has access to webpack config, creating a macro is not high on our priority list. We will happily take contribution if your team has the bandwidth to take this on.
