### ISSUE TITLE
[quilt_rails] - performance report not casting metrics (I think)

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#1493]
## Overview

Some consumers who are using the base `Quilt::Reportable` module from the gem are seeing errors about [rounding strings](https://app.bugsnag.com/shopify/signage/errors/5ed70682b066f60018d9e1dd?filters%5Bevent.since%5D%5B0%5D=30d&filters%5Berror.status%5D%5B0%5D=open) in their bugsnag dashboards. This likely means some data is not getting reported properly.

AFAIK this is a new occurence so it could be related to the PRs which addressed firefox failures.

## Consuming repo
https://github.com/Shopify/signage/blob/master/app/controllers/performance_report_controller.rb#L4

**Comment by b-ryu** [comment]
Took a preliminary look at this, I think the issue seems to be that our report JSON that's sent to the performance controller has numerical values in string form, notably `event` data.

<img width="266" alt="Screen Shot 2020-06-08 at 12 44 49 PM" src="https://user-images.githubusercontent.com/46533681/84057786-2f26b880-a986-11ea-8f8b-4692ad0571ac.png">

This in turn causes an issue when we try to round this string in our [event method](https://github.com/Shopify/quilt/blob/8f68c37790f820b9730aee5724b8f711b83f9ffd/gems/quilt_rails/lib/quilt_rails/performance/event.rb#L57).

The [types](https://github.com/Shopify/quilt/blob/8f68c37790f820b9730aee5724b8f711b83f9ffd/packages/performance/src/types.ts#L16) in `@shopify/performance` suggest that these should be `number`s, and I'm having difficulty reproing in my local branch.

<img width="252" alt="Screen Shot 2020-06-08 at 12 50 36 PM" src="https://user-images.githubusercontent.com/46533681/84058257-f3d8b980-a986-11ea-9360-4b2bafd7923e.png">

Will look into in further detail 👍

**Comment by b-ryu** [comment]
So this seems to be an issue largely caused by deliberately faulty/manually constructed performance reports. Reports sent using defined use cases (Quilt APIs) don't appear to be a factor. Please re-open this issue if problems persist.
