### ISSUE TITLE
@shopify/jest-koa-mocks: context.set is not working 

### ISSUE THREAD

**Issue by gustavkj** [Shopify/quilt#2067]
## Overview

When trying to upgrade `@shopify/jest-koa-mocks` to `3.0.6` our tests break due to `context.set` not using the built-in function anymore due to this change: https://github.com/Shopify/quilt/commit/b16f54290afbaaea70021e1a457e2fefbe5ac403#diff-f8661886e00c5d85521278962660352c556bf2b223429bbf448c467a3e528ea1R115

I cannot read about the origin of the change since there is no PR nor an issue connected to it. If this is how it's intended to work, I'd be grateful to get some help on how to use the built-in `set` function instead or maybe see this added to the readme.

Could it be an option to make this optional? Adding a `useBuiltinSet` option, or something? 🤔 

Side note: I do not have permissions to add labels to this issue.

## Consuming repo

> What repo were you working in when this issue occurred?

It's a repo on a Github Enterprise instance.

**Comment by Krillian111** [comment]
We are facing the exact same problem. It would be good to know if this (breaking?) change was intentional or not as it would affect our decision on how to deal the situation, i.e. rewrite our unit tests, upgrade and use a workaround or delay the upgrade until a fix is available.

A potential quickfix is to overwrite `get` by delegating to the actual `koa` implementation, i.e.
```
import * as Koa from 'koa';
import { createMockContext } from '@shopify/jest-koa-mocks';
// ...
const ctx= createMockContext({...})
ctx.set = (...args: any) => new Koa().context.set.apply(ctx, args);
```

This worked for our tests, not sure how robust this is though.

**Comment by ide** [comment]
Looking at the blame commit, what likely happened is that there were broken tests that removed the context object's prototype chain with`const ctx = {...createMockContext(), locale: ''}`. Without a prototype chain, `ctx.set` wasn't defined. My guess is the author's intent was to fix an error saying, "ctx.set is undefined and not a function."

I put up a PR to change the test cases instead of overwriting `ctx.set`. If flattening the prototype chain is important for some reason, something like `ctx.set = ctx.set` would likely work.
