### ISSUE TITLE
[react-i18n] Allows using short aliases for "i18n.translate"

### ISSUE THREAD

**Issue by claudioc** [Shopify/quilt#2432]
## Overview

For increased DX and terseness of the codebase, it would be nice if we could use a short alias for `i18n.translate`, so that:

```ts
// Instead of
<MyComponent title={i18n.translate('MyComponent.Something')}>

// on could write
<MyComponent title={_t('MyComponent.Something')}>
```

This is in theory possible by aliasing the import of `i18n` from the hook like:

```ts
const [{translate: _t}] = useI18n();
```

but for some reason this is failing with `Cannot destructure property 'pseudolocalize' of 'this' as it is undefined.`. The failure happens [at this exact place](https://github.com/Shopify/quilt/blob/main/packages/react-i18n/src/i18n.ts#L161) as soon as the code tries using `_t()`. This happens inside a child component of `SharedTranslations`, if that could be of interest.

Suggested solutions:
- Is the destructure failure "fixable"? In that case there is nothing to ask for
- Is it possible to just provide an alias at the hook level, so to return `_t` as in `const {_t} = useI18n()`?

## Type

- [x] Changes to existing features

## Motivation

This is for the sake of code readability, without having to mentally skip over a lot of long "i18.translate", which also can save some word wrapping.

**Comment by BPScott** [comment]
> Is the destructure failure "fixable"? In that case there is nothing to ask for

When you do `const [i18n] = useI18n();` i18n is an instance of the I18n class. You can't use destructuring on a class when the class relies upon `this` to reference the other methods on the class because the destructuring destroys the reference to `this`.

Changing I18n from a class to some stateless object is almost certainly not possible as it relies upon a lot of state (see all the stuff that gets set in its constructor) and would be a major breaking change if it was even possible. Thus I do not believe that it is possible to make this change.
