### ISSUE TITLE
Page returns 500 when using react-async and/or react-graphql

### ISSUE THREAD

**Issue by annasfrnv** [Shopify/quilt#717]
## Overview
Marketing team has started seeing [this error on Bugsnag](https://app.bugsnag.com/shopify/shopify-web-client/errors/5cdef28a289de800197ee9c6?filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[search][0][type]=eq&filters[search][0][value]=marketing&filters[search][1][type]=eq&filters[search][1][value]=minified&filters[search][2][type]=eq&filters[search][2][value]=error&filters[search][3][type]=eq&filters[search][3][value]=130) very frequently on marketing-related routes:

```
Element type is invalid: expected a string (for built-in components)
or a class/function (for composite components) but got: object.
``` 

I couldn't reproduce this error neither locally running with production assets nor on prod but @darrenhebner was able to reproduce it on his prod store:

<img width="1920" alt="Screen Shot 2019-05-16 at 10 02 20 AM" src="https://user-images.githubusercontent.com/6495272/58263008-4d088780-7d49-11e9-81f0-4a15da2921ec.png">
At this point JS bundles for marketing were prefetched but the GraphQL query wasn't fired.

Darren has also captured profile of the error: [#130 error.zip](https://github.com/Shopify/quilt/files/3212815/130.error.zip)

Because it was hard to debug this on production, my assumption that this is happening in `react-graphql` because we started seeing error spikes around the same time when I shipped prefetching for Marketing route (May 9th):

<img width="463" alt="Screen Shot 2019-05-23 at 12 05 01 PM" src="https://user-images.githubusercontent.com/6495272/58268214-03bd3580-7d53-11e9-9493-b45fa55c6612.png">

Darren thinks it could be happening in `react-async` package somewhere in https://github.com/Shopify/quilt/blob/9aa1fe9a694019559073ec876a734853599e586b/packages/react-async/src/utilities.ts#L13-L70

## Consuming repo
web on `admin/marketing` and `/admin/discounts/automatic/`

cc: @lemonmade @michelleyschen

**Comment by darrenhebner** [comment]
In order to reproduce it I did the following:
- Refresh Home
- Quickly navigate to Marketing

I saw this error maybe 1 in 10 times.

The stack trace did seem to point in to the async utilities file that Anna mentioned. But I really don't have a clue what causes the error.

**Comment by lemonmade** [comment]
Took a look at this. I could reproduce it, although very infrequently (probably closer to 1 in 20 for me). Just given that, I assumed it was a timing issue. When I took a look under the hood, I found that the error happened while trying to async load the `MarketingIndex` component (via `import('./MarketingIndex')`). The import works fine, but the thing that gets imported is just a `Module` object from Webpack with no exports of any kind (including no default export, which is what is there in the success cases).

I couldn't really figure it out more than that. I suspect that the issue is that there is some script that the page you are navigating from brings in, that downloads after page load, and then that the async import for `MarketingIndex` resolves before that dependency, so you get into a situation similar to some types of cyclical imports where nothing ends up being available (cc/ @GoodForOneFare in case you have smarter ideas of what might be going wrong in Webpack land).

My proposal for this is to just turn the import into a retryable import. This is something I've felt probably makes sense anyways, given that things like random network flakiness can cause scripts to fail flat out already. You'd change your async component creation to look something like:

```tsx
const MarketingIndex = createAsyncComponent({
  load: retryableImport(() =>
    import(/* webpackChunkName: 'marketingIndex' */ './MarketingIndex'),
  ),
  renderLoading: () => <SkeletonMarketingIndex />,
  renderPrefetch: () => (
    <>
      <MarketingIndexQuery.Prefetch variables={DEFAULT_QUERY_VARIABLES} />
      <MarketingRecommendationsQuery.Prefetch
        variables={{
          campaignId: null,
        }}
      />
    </>
  ),
});
```

Where `retryableImport` is something like:

```tsx
function retryableImport<T>(importer: () => Promise<T>): (() => Promise<T>) {
  let retryCount = 0;

  const load = async (): Promise<T> => {
    const imported = await importer();
    const normalized =
      imported &&
      ('default' in imported ? (imported as any).default : imported);

    if (normalized == null || normalized[Symbol.toStringTag] === 'Module') {
      return retry();
    }

    return normalized;
  };

  const retry = (previousError?: Error) => {
    retryCount += 1;

    if (retryCount > MAX_RETRIES) {
      throw previousError || new Error('Failed to load module');
    }

    return new Promise<T>((resolve) =>
      setTimeout(async () => {
        try {
          const result = await load();
          resolve(result);
        } catch (error) {
          resolve(retry(error));
        }
      }, retryCount ** 2 * 50),
    );
  };

  return load;
}
```

I did not verify that this works locally, and I think to truly know if it helps we'd need to roll it to production.

I am away until Tuesday, if you want to investigate this approach feel free to do so 👍
