### ISSUE TITLE
Type Error: Key must be a buffer on verifyRequest

### ISSUE THREAD

**Issue by etnlbck** [Shopify/quilt#772]
## Overview

When hitting `/auth/callback` I'm getting this error: 

` TypeError: Key must be a buffer
      at new Hmac (crypto.js:117:16)
      at Object.createHmac (crypto.js:643:10)
      at Object.validateHmac [as default] (/Users/natelubeck/_projects/_shopify/apps/ozodev/node_modules/@shopify/koa-shopify-auth/dist/auth/validate-hmac.js:17:10)`

### Currently: 
`const generatedHash = crypto
    .createHmac('sha256', secret)
    .update(message)
    .digest('hex');`

### Proposed:
`const generatedHash = crypto
    .createHmac('sha256', secret.toString())
    .update(message)
    .digest('hex');`

https://stackoverflow.com/questions/42569102/typeerror-key-must-be-a-buffer-at-new-hmac-crypto-js9116

**Comment by PaulvdDool** [comment]
Just want to say I've banged my head against the same error for the last few hours until I added the `toString()` to the validateHmac method as suggested here. Error then changed into `cannot read toString of undefined`. Turned out I had named the api key and sectret constants wrong at
`const { SHOPIFY_API_SECRET_KEY, SHOPIFY_API_KEY } = process.env;`. They should be the same as in the `.env` file.
