### ISSUE TITLE
[react-testing] .html(), .toContainReactText() return nothing when testing a Portal

### ISSUE THREAD

**Issue by sylvhama** [Shopify/quilt#835]
## Overview

I have a test sample to reproduce the issue (kudos to @robin-drexler for helping on that):

```jsx
const MyComponent = () => <div>allo</div>;

const element = document.createElement('div');
const MyPortalComponent = () => {
  return ReactDOM.createPortal(<div>allo</div>, element);
};

const rendered = await mountWithAppContext(<MyComponent />);
const renderedPortal = await mountWithAppContext(<MyPortalComponent />);

// Success
expect(rendered).toContainReactText('allo');
// Success
expect(renderedPortal.find('div')).toContainReactText('allo');
// Fail
expect(renderedPortal).toContainReactText('allo');
```

## Consuming repo

> What repo were you working in when this issue occurred?

web

**Comment by lemonmade** [comment]
This is working by design. If the component renders in a portal, its content is not contained by the parent. This assertion only looks at the actual contents of that rendered component; it can’t know where else to look for text that might be in a disconnected node (similar issue was brought up for Toast, which also does not directly render its contents).

**Comment by sylvhama** [comment]
Thanks for those explanations!
