### ISSUE TITLE
proxy({version: ApiVersion.July19}) does not set to set the API Version

### ISSUE THREAD

**Issue by RaphArbuz** [Shopify/quilt#976]
## Overview

I'm trying to register a webhook with @shopify/koa-shopify-webhooks using Shopify CLI but the API version still seem to be April 19 even after setting the version in the proxy and trying to upgrade @shopify/koa-shopify-webhooks to 1.1.13. Any idea why?

Many thanks.

Raphaël

**Comment by RaphArbuz** [comment]
It works fine if I change the line 12 in register.js to:
`case 0: return [4 /*yield*/, fetch("https://" + shop + "/admin/api/2019-07/graphql.json", {`
How come the api version wasn't part of that url before? That could be the source of the bug

**Comment by amardeep9911** [comment]
Having the same issue. There is no way to set the API version in @shopify/koa-shopify-webhooks
Unable to subscribe to APP_SUBSCRIPTIONS_UPDATE webhook which is available only since JULY19 version but the default version in @shopify/koa-shopify-webhooks is APR19 version I guess.

Regarding proxy`({version: ApiVersion.July19})` , I believe that works only for @shopify/koa-shopify-graphql-proxy 

Does anyone have any elegant ideas?

**Comment by nwtn** [comment]
the package has been updated: https://www.npmjs.com/package/@shopify/koa-shopify-webhooks

please upgrade to v2.0.0 and make sure to pass in an API version per the updated README
