### ISSUE TITLE
undefined 'displayName' when asserting a component's existence.

### ISSUE THREAD

**Issue by perrupa** [Shopify/quilt#981]
## Overview

![image](https://user-images.githubusercontent.com/1577452/64643947-90156600-d3df-11e9-8f71-605c1e82d021.png)

I guess the component I'm trying to find has no display name or an instance of it is null somewhere? It doesn't seem that the error is on my end, as the element is either there or not, but an error shouldn't be thrown.

## Consuming repo

[shopify/partners](https://github.com/Shopify/partners)

[Example branch replicating the error](https://github.com/Shopify/partners/compare/failing-test-assertion)

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by michenly** [comment]
2 Action Items:

1️⃣ 
First problem I encounter is `PayoutLayout` is actually a named export, not default export.
But I agree `TypeError: Cannot read property 'displayName' of undefined` is not a very helpful message. 

Ideally we have something like `PayoutLayout is not a ReactComponent` if consumer didnt pass in string.

2️⃣ 
Once I fixed the export problem, the new error are as follow. Which is still not truly helpful.
![Screen Shot 2019-09-19 at 4 45 18 PM](https://user-images.githubusercontent.com/1610169/65281019-97cfbb80-daff-11e9-80a4-578f4112ae34.png)

Ideally we can use the wrapper display name instead of the children, but this may not may not be possible.
ie. `Expected the React element: PayoutDetailsContainer To contain component: PayoutLayout`
