### ISSUE TITLE
Unable to read payload data of webhooks after using  receiveWebhook middleware of @shopify/koa-shopify-webhooks

### ISSUE THREAD

**Issue by amardeepsingh20** [Shopify/quilt#986]
## Overview
In the @shopify/koa-shopify-webhooks package when I use the **receiveWebhook** middleware, I get to see the webhook topic and shop under ctx.state.webhook but I am unable to read the payload data sent by Shopify in the webhook. When I intercept the webhook directly without the **receiveWebhook** middleware, I can read the request body but not when I use the middleware. The ctx seems to strip the payload data.

## Consuming repo
@shopify/koa-shopify-webhooks

**Comment by dan-gamble** [comment]
I think this is because the register webhook doesn't set any included fields by default whereas the REST API sets them all. There doesn't seem to be a way to set the `includeFields` with the `@shopify/koa-shopify-webhooks` package either.

Unfortunately, I had to resort back to the REST API for this.

**Comment by thecodepixi** [comment]
Hey 👋🏻 This issue is _pretty_ old and we've provided new webhooks interface functionality in the [Node API Library](https://github.com/Shopify/shopify-node-api), so I'm going to go ahead and close this. If you still have webhooks after giving the new library a try, please feel free to open a new issue!
